# GCP Secret Manager resources
#
# GitHub App credentials are stored in the centralized secrets hub project
# (var.secrets_hub_project_id, default: or-infra-admin-hub).
# Terraform reads them as data sources and does NOT create local copies.
#
# Cross-project IAM bindings are defined in cross-project-iam.tf:
# - github-app-private-key (read from hub)
# - github-app-id (read from hub)

data "google_secret_manager_secret" "github_app_private_key" {
  project   = var.secrets_hub_project_id
  secret_id = "github-app-private-key"
}

data "google_secret_manager_secret" "github_app_id" {
  project   = var.secrets_hub_project_id
  secret_id = "github-app-id"
}

# ── Railway credentials ───────────────────────────────────────────────────────
# railway-api-token: Stored in secrets hub (pre-populated by pre-bootstrap.sh).
# railway-project-id, railway-environment-id: Created and managed locally
# (populated by deploy-railway.yml workflow after Terraform apply).

resource "google_secret_manager_secret" "railway_project_id" {
  count     = var.enable_railway ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "railway-project-id"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "railway_project_id_access" {
  count     = var.enable_railway ? 1 : 0
  secret_id = google_secret_manager_secret.railway_project_id[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

resource "google_secret_manager_secret" "railway_environment_id" {
  count     = var.enable_railway ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "railway-environment-id"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "railway_environment_id_access" {
  count     = var.enable_railway ? 1 : 0
  secret_id = google_secret_manager_secret.railway_environment_id[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

# ── Cloudflare credentials (for N8N DNS + webhook gateway) ───────────────────
# cloudflare-api-token, cloudflare-zone-id: Stored in secrets hub
# (pre-populated by pre-bootstrap.sh when --enable-cloudflare true).
# Cross-project IAM bindings are defined in cross-project-iam.tf.

# ── N8N secrets ──────────────────────────────────────────────────────────────
# Values auto-generated by populate-secrets.yml workflow (openssl rand).
# Never set here — Terraform only creates the containers + IAM bindings.
# Evidence: project-life-130/terraform/secrets.tf F-IFR-002,
#           populate-secrets.yml generates: openssl rand -hex 32 / -base64 24

resource "google_secret_manager_secret" "n8n_encryption_key" {
  count     = var.enable_n8n ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "n8n-encryption-key"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "n8n_encryption_key_access" {
  count     = var.enable_n8n ? 1 : 0
  secret_id = google_secret_manager_secret.n8n_encryption_key[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

resource "google_secret_manager_secret" "n8n_owner_password" {
  count     = var.enable_n8n ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "n8n-owner-password"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "n8n_owner_password_access" {
  count     = var.enable_n8n ? 1 : 0
  secret_id = google_secret_manager_secret.n8n_owner_password[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

resource "google_secret_manager_secret" "n8n_secrets_broker_token" {
  count     = var.enable_n8n ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "n8n-secrets-broker-token"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "n8n_secrets_broker_token_access" {
  count     = var.enable_n8n ? 1 : 0
  secret_id = google_secret_manager_secret.n8n_secrets_broker_token[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}
