# GCP Secret Manager resources
#
# GATE-001 requires github-app-private-key to be pre-created in GCP SM before
# running Terraform. We reference it as a data source to avoid a conflict on
# apply (creating a resource that already exists returns HTTP 409).
#
# github-app-id is fully managed by Terraform (created + versioned here).

data "google_secret_manager_secret" "github_app_private_key" {
  project   = var.gcp_project_id
  secret_id = "github-app-private-key"
}

resource "google_secret_manager_secret_iam_member" "github_app_key_access" {
  secret_id = data.google_secret_manager_secret.github_app_private_key.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

resource "google_secret_manager_secret" "github_app_id" {
  project   = var.gcp_project_id
  secret_id = "github-app-id"

  replication {
    auto {}
  }
}

resource "google_secret_manager_secret_version" "github_app_id" {
  secret      = google_secret_manager_secret.github_app_id.id
  secret_data = var.github_app_id
}

resource "google_secret_manager_secret_iam_member" "github_app_id_access" {
  secret_id = google_secret_manager_secret.github_app_id.id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

# ── Railway credentials ───────────────────────────────────────────────────────
# Values populated by pre-bootstrap.sh (stored from user-supplied RAILWAY_TOKEN).
# Terraform creates the containers + IAM bindings only.

resource "google_secret_manager_secret" "railway_api_token" {
  count     = var.enable_railway ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "railway-api-token"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "railway_api_token_access" {
  count     = var.enable_railway ? 1 : 0
  secret_id = google_secret_manager_secret.railway_api_token[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

resource "google_secret_manager_secret" "railway_project_id" {
  count     = var.enable_railway ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "railway-project-id"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "railway_project_id_access" {
  count     = var.enable_railway ? 1 : 0
  secret_id = google_secret_manager_secret.railway_project_id[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

resource "google_secret_manager_secret" "railway_environment_id" {
  count     = var.enable_railway ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "railway-environment-id"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "railway_environment_id_access" {
  count     = var.enable_railway ? 1 : 0
  secret_id = google_secret_manager_secret.railway_environment_id[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

# ── Cloudflare credentials (for N8N DNS + webhook gateway) ───────────────────
# Values populated by pre-bootstrap.sh (stored from user-supplied CF_TOKEN).

resource "google_secret_manager_secret" "cloudflare_api_token" {
  count     = var.enable_cloudflare ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "cloudflare-api-token"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "cloudflare_api_token_access" {
  count     = var.enable_cloudflare ? 1 : 0
  secret_id = google_secret_manager_secret.cloudflare_api_token[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

resource "google_secret_manager_secret" "cloudflare_zone_id" {
  count     = var.enable_cloudflare ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "cloudflare-zone-id"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "cloudflare_zone_id_access" {
  count     = var.enable_cloudflare ? 1 : 0
  secret_id = google_secret_manager_secret.cloudflare_zone_id[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

# ── N8N secrets ──────────────────────────────────────────────────────────────
# Values auto-generated by populate-secrets.yml workflow (openssl rand).
# Never set here — Terraform only creates the containers + IAM bindings.
# Evidence: project-life-130/terraform/secrets.tf F-IFR-002,
#           populate-secrets.yml generates: openssl rand -hex 32 / -base64 24

resource "google_secret_manager_secret" "n8n_encryption_key" {
  count     = var.enable_n8n ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "n8n-encryption-key"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "n8n_encryption_key_access" {
  count     = var.enable_n8n ? 1 : 0
  secret_id = google_secret_manager_secret.n8n_encryption_key[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

resource "google_secret_manager_secret" "n8n_owner_password" {
  count     = var.enable_n8n ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "n8n-owner-password"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "n8n_owner_password_access" {
  count     = var.enable_n8n ? 1 : 0
  secret_id = google_secret_manager_secret.n8n_owner_password[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}

resource "google_secret_manager_secret" "n8n_secrets_broker_token" {
  count     = var.enable_n8n ? 1 : 0
  project   = var.gcp_project_id
  secret_id = "n8n-secrets-broker-token"
  replication { auto {} }
}

resource "google_secret_manager_secret_iam_member" "n8n_secrets_broker_token_access" {
  count     = var.enable_n8n ? 1 : 0
  secret_id = google_secret_manager_secret.n8n_secrets_broker_token[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.terraform.email}"
}
